name: Lint and Format Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.ts --fix

      - name: Run Prettier
        run: |
          npx prettier --check "**/*.{js,ts,json,css,md}"
